name: Events Demo
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
         - name: Output  eventdata
           run: echo "${{toJSON(github.event)}}"
         - name: Get code
           run: actions/checkout@v3
         - name: Install dependencies
           run: npm ci

